2016-08-30 10:29:44.454 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:29:44.615 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:29:44.615 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:29:44.615 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:29:44.871 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:31:35.395 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:31:35.528 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:31:35.528 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:31:35.529 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:31:35.773 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:32:25.809 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:32:25.947 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:32:25.947 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:32:25.947 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:32:26.298 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:33:00.095 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:33:00.229 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:33:00.230 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:33:00.230 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:33:00.506 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:33:39.934 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:33:40.061 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:33:40.063 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:33:40.063 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:33:40.324 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:34:30.982 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:34:31.122 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:34:31.122 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:34:31.122 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:34:31.389 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:35:41.520 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:35:41.652 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:35:41.653 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:35:41.653 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:35:41.959 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:35:43.009 [warning] <0.30.0> lager_error_logger_h dropped 185 messages in the last second that exceeded the limit of 50 messages/sec
2016-08-30 10:35:44.005 [warning] <0.30.0> lager_error_logger_h dropped 189 messages in the last second that exceeded the limit of 50 messages/sec
2016-08-30 10:38:59.681 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:38:59.802 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:38:59.803 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:38:59.803 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:39:00.075 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:39:32.363 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:39:32.521 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:39:32.521 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:39:32.521 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:39:32.822 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:40:20.369 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:40:20.572 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:40:20.572 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:40:20.572 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:40:20.836 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:40:57.531 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:40:57.661 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:40:57.661 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:40:57.661 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:40:57.907 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:41:16.156 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:41:16.311 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:41:16.311 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:41:16.311 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:41:16.588 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:43:53.971 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:43:54.109 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:43:54.110 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:43:54.110 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:43:54.571 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:44:17.881 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:44:18.056 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:44:18.057 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:44:18.057 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:44:18.388 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:45:36.555 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:45:36.674 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:45:36.675 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:45:36.675 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:45:36.932 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:46:18.309 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:46:18.445 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:46:18.445 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:46:18.446 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:46:18.714 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-30 10:47:14.557 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:47:14.710 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-30 10:47:14.711 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-30 10:47:14.711 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-30 10:47:15.019 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 10:28:02.055 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-31 10:28:02.304 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-31 10:28:02.305 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-31 10:28:02.305 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-31 10:28:04.849 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 10:29:10.836 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-31 10:29:10.983 [info] <0.31.0> Application lager started on node nonode@nohost
2016-08-31 10:29:10.983 [info] <0.31.0> Application exlager started on node nonode@nohost
2016-08-31 10:29:10.983 [info] <0.31.0> Application riffed started on node nonode@nohost
2016-08-31 10:29:11.447 [info] <0.31.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:12:27.208 [error] <0.210.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.215.0> exit with reason normal in context child_terminated
2016-08-31 15:12:27.372 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:12:27.372 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:12:27.372 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:12:27.481 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in 'Elixir.ElixirThrift.Receiver':init/1 line 2 in gen_server:init_it/6 line 352
2016-08-31 15:12:27.482 [error] <0.261.0> Supervisor 'Elixir.ElixirThrift.Supervisor' had child 'Elixir.ElixirThrift.Receiver' started with 'Elixir.ElixirThrift.Receiver':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.ElixirThrift.Receiver':init/1 line 2 in context start_error
2016-08-31 15:12:27.482 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ElixirThrift.Receiver',{{badmatch,{error,econnrefused}},[{'Elixir.ElixirThrift.Receiver',init,1,[{file,"lib/elixir_thrift/receiver.ex"},{line,2}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{'Elixir.ElixirThrift',start,[normal,[]]}} in application_master:init/4 line 134
2016-08-31 15:13:54.626 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:13:54.778 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:13:54.778 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:13:54.779 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:13:54.882 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in 'Elixir.Tackle':publish/2 line 10 in application_master:init/4 line 134
2016-08-31 15:15:20.441 [error] <0.144.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.149.0> exit with reason normal in context child_terminated
2016-08-31 15:15:20.597 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:15:20.597 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:15:20.598 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:15:20.894 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:18:22.077 [error] <0.210.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.215.0> exit with reason normal in context child_terminated
2016-08-31 15:18:22.219 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:18:22.219 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:18:22.219 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:18:22.233 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:19:48.059 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:19:48.182 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:19:48.182 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:19:48.183 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:19:48.487 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:22:20.396 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:22:20.554 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:22:20.554 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:22:20.554 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:22:20.810 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:22:37.007 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:22:37.121 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:22:37.121 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:22:37.121 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:22:37.172 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:23:56.063 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:23:56.179 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:23:56.179 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:23:56.180 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:23:56.220 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:25:26.914 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:25:27.096 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:25:27.096 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:25:27.097 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:25:27.273 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:28:21.659 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:28:21.787 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:28:21.787 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:28:21.788 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:28:22.341 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:32:58.202 [error] <0.160.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.165.0> exit with reason normal in context child_terminated
2016-08-31 15:32:58.315 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:32:58.316 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:32:58.316 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:32:58.678 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:33:20.154 [error] <0.144.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.149.0> exit with reason normal in context child_terminated
2016-08-31 15:33:20.281 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:33:20.281 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:33:20.281 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:33:20.587 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:33:36.261 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:33:36.380 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:33:36.380 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:33:36.380 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:33:36.760 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 15:33:59.078 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:33:59.203 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 15:33:59.203 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 15:33:59.204 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 15:33:59.227 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: bad argument in thrift_binary_protocol:write/2 line 149 in application_master:init/4 line 134
2016-08-31 16:55:18.305 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.207.0> exit with reason normal in context child_terminated
2016-08-31 16:55:18.830 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 16:55:18.830 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 16:55:18.830 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 16:55:23.006 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
2016-08-31 16:55:58.372 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 16:55:58.639 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-31 16:55:58.639 [info] <0.7.0> Application exlager started on node nonode@nohost
2016-08-31 16:55:58.639 [info] <0.7.0> Application riffed started on node nonode@nohost
2016-08-31 16:55:59.179 [info] <0.7.0> Application elixir_thrift started on node nonode@nohost
